rackspack/config/routes.rb
require 'sidekiq'
require 'sidekiq/web'
Sidekiq::Web.use Rack::Auth::Basic do |username, password|
 [username, password] == ["ashish.mits.gwl@gmail.com","amg@123"]
end
  
Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  resources :members, except: [:destroy]
  devise_for :users
  root to: 'members#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rackspack/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rackspack/app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :member
  belongs_to :friend, :class_name => 'Member'
end

rackspack/app/models/member.rb
require 'nokogiri'
require 'open-uri'
class Member < ApplicationRecord
  attr_accessor :friend_ids
  has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id", dependent: :destroy
  has_many :inverse_friends, :through => :inverse_friendships, :source => :member
  serialize :website_headings
  validates :name, :website_url, presence: true
  after_save :generate_shotern
  
  def friends_list
    friend_ids = self.friends.pluck(:id) + self.inverse_friends.pluck(:id)
    Member.where(id: friend_ids)
  end

  def inverse_friends_list
    Member.where.not(id: friends_list.pluck(:id).push(self.id))
  end

  def all_member_expect_self
    Member.where.not(id: self.id)
  end
  
  def add_friend(friend_id)
    friendships = self.friendships.new(friend_id: friend_id)
    friendships.save
  end

  def remove_all_friends
    self.friends_list.each do |friend|
      self.remove_friend(friend.id)
    end
  end

  def remove_friend(friend_id)
    friendship = self.friendships.where(friend_id: friend_id).first
    if (friendship)
      friendship.destroy
    else
      inverse_friendship = self.inverse_friendships.where(member_id: friend_id).first
      inverse_friendship.destroy
    end
  end

  def is_friend(friend_id)
    self.friends_list.where(id: friend_id).present?
  end

  def update_friends_list(friend_ids)
    if (friend_ids.present?)
      disable_friends = self.friends_list.where.not(id: friend_ids)
      if disable_friends.present?
        disable_friends.each do |disable_friend|
          self.remove_friend(disable_friend.id)
        end
      end
      friend_ids.each do |friend_id|
        self.add_friend(friend_id) unless self.is_friend(friend_id)
      end
    else
      self.remove_all_friends
    end
  end

  def self.wrap_web_content(id)
    member = Member.find_by(id: id)
    doc = Nokogiri::HTML(open(member.website_url))
    header_tags = (1..3).map { |num| "h#{num}" }
    headers = []
    heading_content = doc.css(*header_tags).map do |node|
      headers << node.name
      {'node' => node.name, 'value' => node.text.strip}
    end
    search_content = heading_content.map{|x| x["value"]}.join rescue ""
    member.update_columns(website_headings: heading_content, description: search_content)
  end

  def generate_shotern
    if self.website_url.present?
      client = Bitly::API::Client.new(token: ENV["BITLY_TOKEN"])
      bitlink = client.shorten(long_url: self.website_url)
      self.update_columns(shortening: bitlink.link) 
    end
  end

end

rackspack/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,:recoverable, :rememberable, :validatable
end

rackspack/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true, with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation] )
      devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation])
    end
  
end

rackspack/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update]
  
  def index
    @members = Member.all
  end
  
  def show
    @members = []
    if params[:search].present?
      friends_member_id = @member.friends_list.pluck(:id)
      member_ids = [@member.id, friends_member_id].flatten
      @members = Member.where.not(id: member_ids).where("description LIKE (?)", "%#{params[:search]}%")
    end
  end

  def new
    @member  = Member.new
    @friends = @member.friends_list.pluck(:id)
  end

  def edit
    @friends = @member.friends_list.pluck(:id)
  end

  def create
    @member = Member.new(member_params)
    respond_to do |format|
      if @member.save
        WebContentWorker.perform_async(@member.id)
        format.html { redirect_to edit_member_url(@member), notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      friend_ids = params[:member] && params[:member][:friend_ids] && params[:member][:friend_ids].reject(&:empty?)
      if @member.update(member_params)
        @member.update_friends_list(friend_ids)
        WebContentWorker.perform_async(@member.id)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(:name, :website_url, :shortening, :website_headings, :friend_ids, :description)
    end
end

rackspack/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then "alert alert-info"
    when 'success' then "alert alert-success"
    when 'error' then "alert alert-error"
    when 'alert' then "alert alert-error"
    end
  end
end

rackspack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rackspack</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'shared/stylesheet' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <main class="mt-5 pt-5 mb-5">
      <div class="container">
        <%= render partial: "shared/flash_message" %>
        <%= yield %>
      </div>
    </main>
  </body>
  <%= render 'shared/script' %>
</html>

rackspack/app/views/members/_form.html.erb
<div class="col-md-6 mx-auto">
  <div class="card">
    <h5 class="card-header info-color white-text text-center py-4">
      <strong><%= render partial: "heading_title", locals: {title: form_title}%></strong>
    </h5>
    <%= form_for(member, html: {class: "border border-light p-5 text-center"}) do |form| %>
      <% if member.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>
          <ul>
          <% member.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.text_field :name, class: "form-control mb-4", placeholder: "Name", required: true %>
      </div>
      <div class="field">
        <%= form.text_field :website_url, class: "form-control mb-4", placeholder: "Website URL", required: true %>
      </div>
      <% if action_name.eql?("edit")%>
        <div class="field">
          <%= form.label 'Manage Friends' %>
          <%= form.select :friend_ids, options_for_select(member.all_member_expect_self.collect {|s| [s.name, s.id]}, selected: @friends), {}, id: "friend_ids", :multiple => true  %>
        </div>
      <%end%>
      <div class="actions">
        <%= form.submit "Save", class: "btn btn-info my-4 btn-block" %>
      </div>
    <% end %>
  </div>
</div>


 <script type="text/javascript">
  $( "#friend_ids" ).select2({theme: "bootstrap"});
</script>

rackspack/app/views/members/_heading_title.html.erb
<%= title %>

rackspack/app/views/members/edit.html.erb
<%= render 'form', member: @member, form_title: "Modify Member" %>

rackspack/app/views/members/index.html.erb
<p id="notice"><%= notice %></p>
<h2 class="text-center font-weight-bold">All Members </h2>
<table class="table">
  <thead class="grey lighten-2">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Short URL</th>
      <th scope="col">No. of Friends</th>
      <th scope="col">Manage</th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name.humanize %></td>
        <td><a href="<%= member.shortening %>"><%= member.shortening %></a></td>
         <td><%= member.friends_list.count %></td>
        <td><%= link_to 'Show', member, class: "btn btn-danger text-white btn_list" %>
          <%= link_to 'Edit', edit_member_path(member), class: "btn btn-primary text-white btn_list" %>
        </td>
    <% end %>
  </tbody>
</table>

rackspack/app/views/members/new.html.erb
<%= render 'form', member: @member, form_title: "Add New Member" %>

rackspack/app/views/members/show.html.erb
<div class="row">
  <div class="col-md-8 mx-auto">
    <%= form_tag member_path(id: @member.id), method: "get" do %>
      <%= text_field_tag :search,params[:search], class: "form-control", placeholder: "Experts directory search by topic" %>
    <%end%>
  </div>
</div>
<hr>
<h4 class="font-weight-bold">Member Details</h4>
<hr>
<div class="row">
    <div class="col-md-4">
      <strong>Name: </strong>
      <%= @member.name %>
    </div>
     <div class="col-md-4">
      <strong>Website: </strong>
      <a href="<%= @member.website_url %>"><%= @member.website_url %></a>
    </div>
     <div class="col-md-4">
      <strong>Shortening:</strong>
      <a href="<%= @member.shortening %>"><%= @member.shortening %></a>
    </div>
</div>
<hr>
<% if @members.present? %>
  <div class="row">
    <div class="col-md-12">
      <h4 class="font-weight-bold"></h4>
      <% @members.each do |member| %>
        <div class="row">
          <div class="col-md-3"><%= member.name %></div> 
          <div class="col-md-3">
            <a href="/members/<%= member.id %>">View Profile</a>
          </div>
          <div class="col-md-6">
            <p><%= member.description %></p></div>  
        </div>
      <%end%>
    </div>
  </div>
<%else%>
  <div class="row">
    <div class="col-md-6">
      <h4 class="font-weight-bold">Heading Content</h4>
      <% @member.website_headings.each do |heading| %>
        <%= "<#{heading["node"]}>".html_safe %>
          <%= heading["value"] %>
        <%= "</#{heading["node"]}>".html_safe %>
      <%end%>
    </div>
    <div class="col-md-6">
      <h4 class="font-weight-bold">Friends</h4>
      <% @member.friends_list.each do |friend| %>
        <div class="row">
          <div class="col-md-6"><%= friend.name %></div> 
          <div class="col-md-6">
            <a href="/members/<%= friend.id %>">View Profile</a>
          </div> 
        </div>
      <%end%>
    </div>
  </div>
<%end%>

rackspack/app/views/shared/_flash_message.html.erb
<div class="FlashNotice">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>"> 
      <a class="close" href="#" data-dismiss="alert">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

rackspack/app/views/shared/_navbar.html.erb
<header>
   <nav class="navbar fixed-top navbar-expand-md navbar-light white double-nav scrolling-navbar top-nav-collapse" style="padding-left: unset;">
      <!-- SideNav slide-out button -->
      <!-- Navbar links-->
      <div class="mr-auto pl-2">
         <span class="d-none d-md-inline-block">
           <h3 class="font-weight-bold logo"><a href="/">Expert Directory</a></h3>
         </span>
      </div>
      <!--Navigation icons-->
      <span id="dpl-navbar-right-buttons">
         <!--Navigation icons-->
         <ul class="nav navbar-nav nav-flex-icons ml-auto">
            <% if user_signed_in? %>
               <li class="nav-item d-none d-xl-inline-block" alt="Support" id="navbar-static-support">
                  <a href="/members/new" class="nav-link waves-effect">
                     <i class="fa fa-user"></i><span class="d-none d-xl-inline-block ml-1">Add Member</span>
                  </a>
               </li>
               <li class="nav-item d-none d-xl-inline-block" alt="Support" id="navbar-static-support">
                  <a href="/members" class="nav-link waves-effect">
                     <i class="fa fa-users"></i><span class="d-none d-xl-inline-block ml-1">Member Lists</span>
                  </a>
               </li>
               <a href="<%= destroy_user_session_path %>" id="navbar-static-login" class="btn btn-info btn-rounded btn-sm" data-method="delete">Logout</a>
            <%else%>
               <a href="/users/sign_in" id="navbar-static-login" class="btn btn-info btn-rounded btn-sm waves-effect" >Login</a>
            <%end%>
         </ul>
      </span>
   </nav>
   <!-- /.Navbar-->
</header>

rackspack/app/views/shared/_script.html.erb
<%= javascript_include_tag 'popper.min.js' %>
<%= javascript_include_tag 'bootstrap.min.js' %>
<%= javascript_include_tag 'mdb.js' %>

rackspack/app/views/shared/_stylesheet.html.erb
<link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans|PT+Sans|PT+Serif|Raleway|Roboto|Rubik|Work+Sans" rel="stylesheet"> 
<link  rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">